### PR TITLE
Python3

### PR DESCRIPTION
**Pull request by jamesba**
Added support for pythons 2 and 3

### CODE REVIEW

**Comment by simonrankine** [comment]
Have you tried running this on an IP Studio machine to check it all looks okay on there @jamesba?

**Comment by simonrankine** [comment]
For the benefit of those that may come after, could you please outline what tooling you've used to do this, and a rough outline of the changes you needed to make please?

**Comment by simonrankine** [comment]
Note to self - tested this with nmos-joint-ri. Worked okay.

**Comment by jamesba** [comment]
I did this primarily by running the tests in python3 and seeing what exceptions where thrown.

Most places where syntax differs significantly from python2 the six library was used to provide a stable non-version specific interface.

**Comment by simonrankine** [comment]
When I build the deb for this I get this error from lintian https://lintian.debian.org/tags/build-depends-on-1-revision.html

You seem to be requiring python3-setuptools >=20.7.0-1, is there any reason it can't just be >=20.7.0?

**Comment by simonrankine** [comment]
Tested on an ipstudio machine - looks good as far as I can tell there

**Pull request merged**
