### PR TITLE
Get rid of fixed dependancy versions

### PR DESCRIPTION
**Pull request by j616**

### CODE REVIEW

**Comment by simonrankine** [comment]
Have you integration tested this with the joint-ri to make sure no smoke comes out?

**Comment by j616** [comment]
`Pybonjour isn't available from pip (despite how it appears), hence why we required exactly that version and the extra tarball download.`
Will fix this

`I'm a little concerned that we had an upper restriction on python-dateutil and this has been removed without any code modifications. Can you trace when this was added in order to identify why?`
This was added when the unit tests were added along with all the other fixed versions. python-dateutil 2.7.0 is significant as it removed support for python 2.7 and 3.2. When discussing this with @jamesba yesterday, we think this shouldn't be a problem because compatible versions should be installed by pip if using `pip` or `pip3` or with the relevant deb. @jamesba had a vague memory that there may have been another reason for locking the version at the time related to compatibility with the other dependencies. That doesn't seem to be an issue now.

`Assuming running this with latest flask (and flask related) libraries doesn't cause unit test errors, as Simon suggests we should test it together with the RI.`
This has been tested on the RI and seems to work. Would appreciate someone double checking, though.

**Comment by simonrankine** [comment]
Note to self, check that trailing slashes still redirect correctly

**Comment by j616** [comment]
Added pybonjour deps_required back in

**Pull request merged**
