### PR TITLE
Added Authorzation header for Cross Site requests (CORS)

### PR DESCRIPTION
**Pull request by dannymeloy**

### CODE REVIEW

**Comment by dannymeloy** [comment]
Updated the tests as a flurry of them failed expecting the relevant CORS headers to line up. They seem to pass when run on my machine

**Comment by andrewbonney** [comment]
Any reason for removing 'self' passed in to 'add_routes'? Doesn't look like it'll make a difference in this case, but I'm just wondering if anything else external might call add_routes at some point?

**Comment by dannymeloy** [comment]
Could this be merged as is or do I need to write some tests for the Authlib errorhandlers?

**Comment by andrewbonney** [comment]
I'm happy with it as is, but it will need the config defaults adding to setup.py, and the new dependency adding to stdeb.cfg

**Comment by andrewbonney** [comment]
Looks good. Just needs a changelog entry and modification to setup.py (I'd suggest changing the minor version number). When it's merged it's probably worth using 'squash and merge' given there are quite a few commits here and they're all along the same theme.

**Pull request merged**
